### ISSUE TITLE
Error on parsing "first", "second", "third" etc.

### ISSUE THREAD

**Issue by rutvij-rajdeo** [akshaynagpal/w2n#31] opened 2018-10-16 05:41 UTC
>>> w2n.word_to_num("third")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/word2number/w2n.py", line 154, in word_to_num
    raise ValueError("No valid number words found! Please enter a valid number word (eg. two million twenty three thousand and forty nine)") 
ValueError: No valid number words found! Please enter a valid number word (eg. two million twenty three thousand and forty nine)
>>>

**Comment by akshaynagpal** [comment] 2018-10-22 02:04
Duplicate of #10 . This is a feature request.

**Closed as completed by akshaynagpal** 2018-10-22 02:04 UTC
Labels: duplicate
